---
- name: "Install NodeJS and NPM"
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: Copy files to EC2 instance
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "Install, Build and Start server"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build
    npm start
