---
- name: "Install NodeJS and NPM"
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: "Install, Build and Start server"
  become: true
  shell: |
    cp /root/project/backend /home/ubuntu
    cd /home/ubuntu/backend
    npm i
    npm run build
    npm start
