Description: >
  UdaPeople Prometheus stack.

Resources:
  PrometheusSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: PrometheusSG
      GroupDescription: Allow relevant prometheus ports.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5532
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9093
          ToPort: 9093
          CidrIp: 0.0.0.0/0

  PrometheusInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: PrometheusSG
      KeyName: udacity
      ImageId: ami-07dd19a7900a1f049 
      Tags:
        - Key: Name
          Value: prometheus
